apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/roming22/pipelines-service/my/gitops/gitops/plnsvc/base/namespace.yaml
  - https://raw.githubusercontent.com/roming22/pipelines-service/my/gitops/gitops/plnsvc/base/kcp-syncer.yaml
  - https://raw.githubusercontent.com/roming22/pipelines-service/my/gitops/kcp/manifests/plnsvc/argocd-manager.yaml
